### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tobydarkh** [dalcib/expo-ts-example#5]
Hey,

when i download the repo and make a "yarn" inside and start it with "yarn start" and open it then with the Expo App on my iPhone 7 Plus iOS 11 i get following Error:

undefined is not an object (evaluating '_globalWindow2['default'].__reactComponentProxies')

_<unknown>
C:\Users\Tobias\Desktop\myApp\node_modules\react-transform-hmr\lib\index.js:20:30
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
<unknown file>:0
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\node_modules\@expo\vector-icons\MaterialIcons.js:3
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\src\App.tsx:3
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\App.js:1
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\node_modules\react-native-scripts\build\bin\crna-entry.js:27:19
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
guardedLoadModule
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:123:45
global code
<unknown file>:0
<unknown>
C:\Users\Tobias\Desktop\myApp\node_modules\react-transform-hmr\lib\index.js:20:30
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
<unknown file>:0
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\node_modules\@expo\vector-icons\MaterialIcons.js:3
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\src\App.tsx:3
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\App.js:1
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
<unknown>
C:\Users\Tobias\Desktop\myApp\node_modules\react-native-scripts\build\bin\crna-entry.js:27:19
loadModuleImplementation
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:178:12
guardedLoadModule
C:\Users\Tobias\Desktop\myApp\node_modules\metro-bundler\src\Resolver\polyfills\require.js:123:45
global code
<unknown file>:0_

Have you an Idea to Fix it?

**Comment by dalcib** [comment]
I have tried but I didn't get the solution. Sine times delete nide_modules and run yarn works, but not always. I didn't try npm yet.
